trigger:
  branches:
    include:
      - master




stages:
- stage: approval
  jobs:
  - deployment: Process
    environment: 'Approval'
    

- stage: build
  dependsOn: 
  - approval
  condition: succeeded('approval')
  jobs:
  - job:
    steps:
    - script: |
        echo hello
      displayName: 'Loop through myMapVariable'
              

- stage: deploy
  dependsOn: 
  - approval
  - build
  condition: and(succeeded('build'),succeeded('approval'))
  jobs:
  - job:
    steps:
    - script: |
        echo 'ok that is it'
      displayName: 'push image'
      
- stage: check
  dependsOn: 
  - approval
  - build
  condition: and(succeeded('deploy'),succeeded('approval'))
  jobs:
  - job:
    steps:
    - script: |
        echo 'ok that is it'
      displayName: 'push image'
- 