trigger:
  branches:
    include:
      - master


parameters:
  - name: DOCKERHYB_PASSWORD_VALUE
    type: string
    default: ''


variables:
   IMAGE_NAME: simple-app
   ACCOUNT_NAME: elmansey
   DOCKERHUB_USERNAME: elmansey
   DOCKERHYB_PASSWORD: ${{ parameters.DOCKERHYB_PASSWORD_VALUE }}


stages:
- stage: build
  jobs:
  - deployment: Process
    environment: 'Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              docker build -t $(ACCOUNT_NAME)/$(IMAGE_NAME):$(Build.BuildId) . 
            displayName: 'build image'
              
- stage: deploy
  dependsOn: 
  - build
  jobs:
  - job:
      steps:
        - script: |
            echo 'ok that is it'
          displayName: 'push image'
      

   
