trigger:
  branches:
    include:
      - master

variables:
   IMAGE_NAME: simple-app
   ACCOUNT_NAME: elmansey


stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          docker build -t $(ACCOUNT_NAME)/$(IMAGE_NAME):$(Build.BuildId) . 
        displayName: 'build image'
