trigger:
  branches:
    include:
      - master

parameters:
- name: sslCerts
  type: object 
  default:
    Development:
      sslCertificate: service1-dev.p12
      sslCertificateKey: service1-dev
    Sandbox:
      sslCertificate: service1-sbxdev.p12
      sslCertificateKey: service-sbxdev-key

variables:
  myMapVariable:
    sandbox: value1
    prod: value2
    non-prod: value3





stages:
- stage: build
  jobs:
  - deployment: Process
    environment: 'Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Looping through myMapVariable"
              ${{ each key, value in variables.myMapVariable }}:
                echo "Key: ${{ key }}, Value: ${{ value }}"
            displayName: 'Loop through myMapVariable'
              
- stage: deploy
  dependsOn: build
  jobs:
  - job:
    steps:
    - script: |
        echo 'ok that is it'
      displayName: 'push image'
      

   
