trigger:
  branches:
    include:
      - master
stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: buildAndPush
        repository: 'elmansey/app-simple'
        tags: 'latest'
        Dockerfile: '**/Dockerfile'
