trigger:
  branches:
    include:
      - master


parameters:
  - name: DOCKERHYB_PASSWORD_VALUE
    type: string
    default: ''


variables:
   IMAGE_NAME: simple-app
   ACCOUNT_NAME: elmansey
   DOCKERHUB_USERNAME: elmansey
   DOCKERHYB_PASSWORD: ${{ parameters.DOCKERHYB_PASSWORD_VALUE }}


stages:
  - stage: deploy
    jobs:
    - deployment: Process
      environment: Site Engineering Approval
      pool:
        vmImage: Ubuntu-20.04
        displayName: test
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  docker build -t $(ACCOUNT_NAME)/$(IMAGE_NAME):$(Build.BuildId) . 
                displayName: 'build image'
              - script: |
                  docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHYB_PASSWORD)
                  docker push $(ACCOUNT_NAME)/$(IMAGE_NAME):$(Build.BuildId)
                displayName: 'push image'
        

   
