trigger:
  branches:
    include:
      - master


parameters:
  - name: name
    type: string
    default: ''


variables:
   name: ${{ parameters.name }}


stages:
- stage: build
  jobs:
  - deployment: Process
    environment: 'Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo  'hello $(name)'
            displayName: 'build image'
              
- stage: deploy
  dependsOn: build
  jobs:
  - job:
    steps:
    - script: |
        echo 'ok that is it'
      displayName: 'push image'
      

   
