trigger:
  branches:
    include:
      - master

# parameters:
# - name: sslCerts
#   type: object 
#   default:
#     Development:
#       sslCertificate: service1-dev.p12
#       sslCertificateKey: service1-dev
#     Sandbox:
#       sslCertificate: service1-sbxdev.p12
#       sslCertificateKey: service-sbxdev-key

parameters:
- name: sslCerts
  type: object 
  default:
    Development:
      sandbox: service1-dev.p12
      prod: service1-dev
      non-prod: sdsdsfsf




stages:
- stage: build
  jobs:
  - deployment: Process
    environment: 'Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
             echo $(parameters.Development['sandbox'])
            displayName: 'Loop through myMapVariable'
              
- stage: deploy
  dependsOn: build
  jobs:
  - job:
    steps:
    - script: |
        echo 'ok that is it'
      displayName: 'push image'
      

   
