trigger:
  branches:
    include:
      - master


parameters:
  - name: DOCKERHYB_PASSWORD_VALUE
    type: string
    default: ''


variables:
   IMAGE_NAME: simple-app
   ACCOUNT_NAME: elmansey
   DOCKERHUB_USERNAME: elmansey
   DOCKERHYB_PASSWORD: ${{ parameters.DOCKERHYB_PASSWORD_VALUE }}

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          docker build -t $(ACCOUNT_NAME)/$(IMAGE_NAME):$(Build.BuildId) . 
        displayName: 'build image'
      - script: |
          docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHYB_PASSWORD)
          docker push $(ACCOUNT_NAME)/$(IMAGE_NAME):$(Build.BuildId)
        displayName: 'push image'
        
- stage: ApprovalStage
  displayName: Approval Stage
  jobs:
  - job: ApprovalJob
    displayName: Approval Job
    steps:
    - task: ManualIntervention
      inputs:
        instructions: 'Please review and approve the pipeline run.'


